// Car data stored directly in JavaScript
const carData = [
    {
        "id": "astonmartin-db11",
        "name": "Aston Martin DB11",
        "brand": "Aston Martin",
        "model": "DB11",
        "year": 2023,
        "type": "Grand Tourer",
        "price": 205600,
        "image": "/images/aston martin db11.jpeg",
        "description": "A grand tourer with a V12 engine and timeless British design.",
        "specs": {
          "engine": "5.2L V12",
          "power": "630 hp",
          "torque": "516 lb-ft",
          "acceleration": "3.7s",
          "topSpeed": "208 mph",
          "weight": "1870 kg",
          "length": "4750 mm",
          "width": "1950 mm",
          "height": "1290 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Adaptive Damping",
          "Leather Interior",
          "Bang & Olufsen Audio",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Magnetic Silver",
          "Onyx Black",
          "Marron Black",
          "Frosted Glass Blue",
          "China Grey"
        ],
        "rating": 4.8,
        "reviews": 321,
        "featured": true
      },
      {
        "id": "astonmartin-vantage",
        "name": "Aston Martin Vantage",
        "brand": "Aston Martin",
        "model": "Vantage",
        "year": 2022,
        "type": "Sports Coupe",
        "price": 139000,
        "image": "/images/Aston Martin Vantage.jpeg",
        "description": "A sharp, agile sports car with a twin-turbo V8.",
        "specs": {
          "engine": "4.0L Twin-Turbo V8",
          "power": "503 hp",
          "torque": "505 lb-ft",
          "acceleration": "3.6s",
          "topSpeed": "195 mph",
          "weight": "1530 kg",
          "length": "4465 mm",
          "width": "1942 mm",
          "height": "1273 mm",
          "seats": "2",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Sport Suspension",
          "Premium Audio",
          "Heated Seats",
          "Rear Camera",
          "Navigation"
        ],
        "colors": [
          "Lime Essence",
          "Jet Black",
          "China Grey",
          "Cinnabar Orange",
          "Skyfall Silver"
        ],
        "rating": 4.7,
        "reviews": 210,
        "featured": false
      },
      {
        "id": "astonmartin-dbs-superleggera",
        "name": "Aston Martin DBS Superleggera",
        "brand": "Aston Martin",
        "model": "DBS Superleggera",
        "year": 2021,
        "type": "Super GT",
        "price": 316300,
        "image": "/images/Aston Martin DBS Superleggera.jpeg",
        "description": "A flagship GT with immense power and luxury.",
        "specs": {
          "engine": "5.2L Twin-Turbo V12",
          "power": "715 hp",
          "torque": "664 lb-ft",
          "acceleration": "3.4s",
          "topSpeed": "211 mph",
          "weight": "1845 kg",
          "length": "4712 mm",
          "width": "1968 mm",
          "height": "1280 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Carbon Fiber Trim",
          "Bang & Olufsen Audio",
          "Adaptive Cruise",
          "Leather Interior",
          "Navigation"
        ],
        "colors": [
          "Xenon Grey",
          "Onyx Black",
          "Hyper Red",
          "Frosted Glass Blue",
          "Scintilla Silver"
        ],
        "rating": 4.9,
        "reviews": 98,
        "featured": false
      },
      {
        "id": "astonmartin-rapide",
        "name": "Aston Martin Rapide AMR",
        "brand": "Aston Martin",
        "model": "Rapide AMR",
        "year": 2020,
        "type": "Luxury Sedan",
        "price": 240000,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "A four-door sports car with V12 power and luxury.",
        "specs": {
          "engine": "6.0L V12",
          "power": "580 hp",
          "torque": "465 lb-ft",
          "acceleration": "4.2s",
          "topSpeed": "205 mph",
          "weight": "1990 kg",
          "length": "5019 mm",
          "width": "1929 mm",
          "height": "1350 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "AMR Styling",
          "Premium Audio",
          "Rear Entertainment",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Stirling Green",
          "Scintilla Silver",
          "Onyx Black",
          "White Stone",
          "Lime Essence"
        ],
        "rating": 4.6,
        "reviews": 45,
        "featured": false
      },
      {
        "id": "astonmartin-valkyrie",
        "name": "Aston Martin Valkyrie",
        "brand": "Aston Martin",
        "model": "Valkyrie",
        "year": 2022,
        "type": "Hypercar",
        "price": 3200000,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A hybrid hypercar with F1 technology and extreme performance.",
        "specs": {
          "engine": "6.5L V12 Hybrid",
          "power": "1160 hp",
          "torque": "664 lb-ft",
          "acceleration": "2.5s",
          "topSpeed": "250 mph",
          "weight": "1030 kg",
          "length": "4500 mm",
          "width": "1950 mm",
          "height": "1127 mm",
          "seats": "2",
          "transmission": "7-speed Automated Manual",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Hybrid"
        },
        "features": [
          "F1-Inspired Aerodynamics",
          "Carbon Fiber Monocoque",
          "Track Mode",
          "Lightweight Seats",
          "Touchscreen Display"
        ],
        "colors": [
          "Cosmos Orange",
          "Liquid Silver",
          "Meteorite Silver",
          "Lime Essence",
          "Onyx Black"
        ],
        "rating": 5.0,
        "reviews": 12,
        "featured": true
      },
      {
        "id": "bmw-m4",
        "name": "BMW M4",
        "brand": "BMW",
        "model": "M4",
        "year": 2024,
        "type": "Sports Coupe",
        "price": 74900,
        "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop",
        "description": "The BMW M4 is the ultimate expression of BMW's M division, combining raw power with precision engineering.",
        "specs": {
          "engine": "3.0L Twin-Turbo I6",
          "power": "473 hp",
          "torque": "406 lb-ft",
          "acceleration": "3.8s",
          "topSpeed": "180 mph",
          "weight": "1730 kg",
          "length": "4794 mm",
          "width": "1887 mm",
          "height": "1393 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "M Adaptive Suspension",
          "M Sport Exhaust",
          "19-inch M Wheels",
          "M Sport Seats",
          "Head-up Display"
        ],
        "colors": [
          "Alpine White",
          "Black Sapphire",
          "Isle of Man Green",
          "Toronto Red",
          "Frozen Black"
        ],
        "rating": 4.7,
        "reviews": 892,
        "featured": true
      },
      {
        "id": "bmw-i8",
        "name": "BMW i8",
        "brand": "BMW",
        "model": "i8",
        "year": 2020,
        "type": "Hybrid Sports Car",
        "price": 147500,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "A futuristic plug-in hybrid sports car with striking looks.",
        "specs": {
          "engine": "1.5L Turbo I3 Hybrid",
          "power": "369 hp",
          "torque": "420 lb-ft",
          "acceleration": "4.2s",
          "topSpeed": "155 mph",
          "weight": "1560 kg",
          "length": "4689 mm",
          "width": "1942 mm",
          "height": "1298 mm",
          "seats": "4",
          "transmission": "6-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Hybrid"
        },
        "features": [
          "Laser Headlights",
          "Carbon Fiber Chassis",
          "Harman Kardon Audio",
          "Navigation",
          "Heated Seats"
        ],
        "colors": [
          "Crystal White",
          "Sophisto Grey",
          "Protonic Blue",
          "E-Copper",
          "Frozen Black"
        ],
        "rating": 4.6,
        "reviews": 312,
        "featured": false
      },
      {
        "id": "bmw-x7",
        "name": "BMW X7",
        "brand": "BMW",
        "model": "X7",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 92900,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "BMW's flagship luxury SUV with three rows and advanced tech.",
        "specs": {
          "engine": "3.0L Turbo I6",
          "power": "375 hp",
          "torque": "398 lb-ft",
          "acceleration": "5.8s",
          "topSpeed": "155 mph",
          "weight": "2440 kg",
          "length": "5151 mm",
          "width": "2000 mm",
          "height": "1805 mm",
          "seats": "7",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Panoramic Roof",
          "Heated/Cooled Seats",
          "Bowers & Wilkins Audio",
          "Gesture Control",
          "Adaptive Cruise"
        ],
        "colors": [
          "Mineral White",
          "Arctic Grey",
          "Black Sapphire",
          "Phytonic Blue",
          "Vermont Bronze"
        ],
        "rating": 4.8,
        "reviews": 210,
        "featured": true
      },
      {
        "id": "bmw-m5-cs",
        "name": "BMW M5 CS",
        "brand": "BMW",
        "model": "M5 CS",
        "year": 2022,
        "type": "Super Sedan",
        "price": 142000,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "The most powerful BMW M5 ever, with track-ready performance.",
        "specs": {
          "engine": "4.4L Twin-Turbo V8",
          "power": "627 hp",
          "torque": "553 lb-ft",
          "acceleration": "2.9s",
          "topSpeed": "190 mph",
          "weight": "1825 kg",
          "length": "4983 mm",
          "width": "1903 mm",
          "height": "1473 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Carbon Ceramic Brakes",
          "M Carbon Seats",
          "Laser Headlights",
          "Track Mode",
          "Navigation"
        ],
        "colors": [
          "Frozen Deep Green",
          "Brands Hatch Grey",
          "Black Sapphire",
          "Frozen White",
          "Imola Red"
        ],
        "rating": 4.9,
        "reviews": 98,
        "featured": false
      },
      {
        "id": "bmw-z4",
        "name": "BMW Z4 Roadster",
        "brand": "BMW",
        "model": "Z4",
        "year": 2023,
        "type": "Convertible",
        "price": 52900,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "A stylish, open-top roadster with classic BMW handling.",
        "specs": {
          "engine": "2.0L Turbo I4",
          "power": "255 hp",
          "torque": "295 lb-ft",
          "acceleration": "5.2s",
          "topSpeed": "155 mph",
          "weight": "1495 kg",
          "length": "4324 mm",
          "width": "1864 mm",
          "height": "1304 mm",
          "seats": "2",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "M Sport Package",
          "Wind Deflector",
          "Heated Seats",
          "Harman Kardon Audio",
          "Navigation"
        ],
        "colors": [
          "San Francisco Red",
          "Alpine White",
          "Misano Blue",
          "Black Sapphire",
          "Glacier Silver"
        ],
        "rating": 4.5,
        "reviews": 120,
        "featured": false
      },
      {
        "id": "ferrari-f8",
        "name": "Ferrari F8 Tributo",
        "brand": "Ferrari",
        "model": "F8 Tributo",
        "year": 2024,
        "type": "Supercar",
        "price": 276550,
        "image": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=600&fit=crop",
        "description": "The Ferrari F8 Tributo is the latest evolution of Ferrari's mid-engine V8 sports car.",
        "specs": {
          "engine": "3.9L Twin-Turbo V8",
          "power": "710 hp",
          "torque": "568 lb-ft",
          "acceleration": "2.9s",
          "topSpeed": "211 mph",
          "weight": "1435 kg",
          "length": "4611 mm",
          "width": "1979 mm",
          "height": "1206 mm",
          "seats": "2",
          "transmission": "7-speed F1 DCT",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Ferrari Dynamic Enhancer",
          "Side Slip Angle Control",
          "Carbon Fiber Interior",
          "Ferrari Telemetry",
          "Racing Seats"
        ],
        "colors": [
          "Bianco Avus",
          "Nero Daytona",
          "Rosso Corsa",
          "Giallo Modena",
          "Verde Racing"
        ],
        "rating": 4.9,
        "reviews": 423,
        "featured": true
      },
      {
        "id": "ferrari-roma",
        "name": "Ferrari Roma",
        "brand": "Ferrari",
        "model": "Roma",
        "year": 2023,
        "type": "Grand Tourer",
        "price": 222620,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A V8-powered grand tourer with elegant design and modern tech.",
        "specs": {
          "engine": "3.9L Twin-Turbo V8",
          "power": "612 hp",
          "torque": "561 lb-ft",
          "acceleration": "3.3s",
          "topSpeed": "199 mph",
          "weight": "1570 kg",
          "length": "4656 mm",
          "width": "1974 mm",
          "height": "1301 mm",
          "seats": "4",
          "transmission": "8-speed DCT",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Magneride Suspension",
          "Apple CarPlay",
          "Leather Interior",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Blu Roma",
          "Rosso Corsa",
          "Grigio Silverstone",
          "Nero Daytona",
          "Bianco Avus"
        ],
        "rating": 4.8,
        "reviews": 210,
        "featured": false
      },
      {
        "id": "ferrari-sf90",
        "name": "Ferrari SF90 Stradale",
        "brand": "Ferrari",
        "model": "SF90 Stradale",
        "year": 2022,
        "type": "Hybrid Supercar",
        "price": 507000,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "A plug-in hybrid supercar with blistering performance.",
        "specs": {
          "engine": "4.0L Twin-Turbo V8 Hybrid",
          "power": "986 hp",
          "torque": "590 lb-ft",
          "acceleration": "2.5s",
          "topSpeed": "211 mph",
          "weight": "1570 kg",
          "length": "4710 mm",
          "width": "1972 mm",
          "height": "1186 mm",
          "seats": "2",
          "transmission": "8-speed DCT",
          "drivetrain": "All-wheel drive",
          "fuelType": "Hybrid"
        },
        "features": [
          "Plug-in Hybrid",
          "E-Manettino",
          "Carbon Fiber Wheels",
          "Track Mode",
          "Touchscreen Display"
        ],
        "colors": [
          "Rosso Scuderia",
          "Giallo Modena",
          "Blu Corsa",
          "Nero Daytona",
          "Argento Nurburgring"
        ],
        "rating": 5.0,
        "reviews": 99,
        "featured": true
      },
      {
        "id": "ferrari-portofino",
        "name": "Ferrari Portofino M",
        "brand": "Ferrari",
        "model": "Portofino M",
        "year": 2022,
        "type": "Convertible",
        "price": 226000,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "A retractable hardtop convertible with V8 power and style.",
        "specs": {
          "engine": "3.9L Twin-Turbo V8",
          "power": "612 hp",
          "torque": "561 lb-ft",
          "acceleration": "3.5s",
          "topSpeed": "199 mph",
          "weight": "1664 kg",
          "length": "4594 mm",
          "width": "1938 mm",
          "height": "1318 mm",
          "seats": "4",
          "transmission": "8-speed DCT",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Retractable Hardtop",
          "Magneride Suspension",
          "Apple CarPlay",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Rosso Portofino",
          "Blu Tour De France",
          "Grigio Titanio",
          "Nero Daytona",
          "Bianco Avus"
        ],
        "rating": 4.7,
        "reviews": 120,
        "featured": false
      },
      {
        "id": "ferrari-812",
        "name": "Ferrari 812 Superfast",
        "brand": "Ferrari",
        "model": "812 Superfast",
        "year": 2021,
        "type": "Super GT",
        "price": 335000,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A front-engine V12 grand tourer with immense power.",
        "specs": {
          "engine": "6.5L V12",
          "power": "789 hp",
          "torque": "530 lb-ft",
          "acceleration": "2.8s",
          "topSpeed": "211 mph",
          "weight": "1630 kg",
          "length": "4657 mm",
          "width": "1971 mm",
          "height": "1276 mm",
          "seats": "2",
          "transmission": "7-speed DCT",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Rear-Wheel Steering",
          "Carbon Fiber Trim",
          "Brembo Brakes",
          "Leather Interior",
          "Navigation"
        ],
        "colors": [
          "Rosso Corsa",
          "Giallo Modena",
          "Blu Scozia",
          "Nero Daytona",
          "Grigio Silverstone"
        ],
        "rating": 4.9,
        "reviews": 88,
        "featured": false
      },
      {
        "id": "lamborghini-huracan-evo",
        "name": "Lamborghini Huracán EVO",
        "brand": "Lamborghini",
        "model": "Huracán EVO",
        "year": 2023,
        "type": "Supercar",
        "price": 208571,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A naturally aspirated V10 supercar with Italian flair and performance.",
        "specs": {
          "engine": "5.2L V10",
          "power": "631 hp",
          "torque": "443 lb-ft",
          "acceleration": "2.9s",
          "topSpeed": "202 mph",
          "weight": "1422 kg",
          "length": "4520 mm",
          "width": "1933 mm",
          "height": "1165 mm",
          "seats": "2",
          "transmission": "7-speed LDF",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "LDVI System",
          "Magnetorheological Suspension",
          "Carbon Ceramic Brakes",
          "Apple CarPlay",
          "Navigation"
        ],
        "colors": [
          "Arancio Xanto",
          "Verde Mantis",
          "Giallo Inti",
          "Blu Nethuns",
          "Grigio Lynx"
        ],
        "rating": 4.9,
        "reviews": 389,
        "featured": true
      },
      {
        "id": "lamborghini-aventador-svj",
        "name": "Lamborghini Aventador SVJ",
        "brand": "Lamborghini",
        "model": "Aventador SVJ",
        "year": 2021,
        "type": "Hypercar",
        "price": 517770,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "A V12-powered hypercar with extreme aerodynamics and performance.",
        "specs": {
          "engine": "6.5L V12",
          "power": "759 hp",
          "torque": "531 lb-ft",
          "acceleration": "2.8s",
          "topSpeed": "217 mph",
          "weight": "1525 kg",
          "length": "4943 mm",
          "width": "2098 mm",
          "height": "1136 mm",
          "seats": "2",
          "transmission": "7-speed ISR",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "ALA 2.0 Aerodynamics",
          "Carbon Fiber Monocoque",
          "Magnetorheological Suspension",
          "Apple CarPlay",
          "Navigation"
        ],
        "colors": [
          "Giallo Orion",
          "Rosso Mars",
          "Bianco Isis",
          "Nero Aldebaran",
          "Blu Glauco"
        ],
        "rating": 5.0,
        "reviews": 77,
        "featured": true
      },
      {
        "id": "lamborghini-urus",
        "name": "Lamborghini Urus",
        "brand": "Lamborghini",
        "model": "Urus",
        "year": 2023,
        "type": "Super SUV",
        "price": 225500,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "A high-performance SUV with Lamborghini DNA.",
        "specs": {
          "engine": "4.0L Twin-Turbo V8",
          "power": "641 hp",
          "torque": "627 lb-ft",
          "acceleration": "3.6s",
          "topSpeed": "190 mph",
          "weight": "2200 kg",
          "length": "5112 mm",
          "width": "2016 mm",
          "height": "1638 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "ANIMA Drive Modes",
          "Bang & Olufsen Audio",
          "Panoramic Roof",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Giallo Auge",
          "Blu Eleos",
          "Nero Helene",
          "Bianco Monocerus",
          "Grigio Lynx"
        ],
        "rating": 4.8,
        "reviews": 210,
        "featured": false
      },
      {
        "id": "lamborghini-gallardo",
        "name": "Lamborghini Gallardo LP560-4",
        "brand": "Lamborghini",
        "model": "Gallardo LP560-4",
        "year": 2014,
        "type": "Supercar",
        "price": 202000,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A classic V10 supercar with all-wheel drive and iconic design.",
        "specs": {
          "engine": "5.2L V10",
          "power": "552 hp",
          "torque": "398 lb-ft",
          "acceleration": "3.7s",
          "topSpeed": "202 mph",
          "weight": "1410 kg",
          "length": "4345 mm",
          "width": "1900 mm",
          "height": "1165 mm",
          "seats": "2",
          "transmission": "6-speed E-gear",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "All-Wheel Drive",
          "Navigation",
          "Leather Interior",
          "Heated Seats",
          "Sport Exhaust"
        ],
        "colors": [
          "Giallo Midas",
          "Arancio Borealis",
          "Verde Ithaca",
          "Bianco Monocerus",
          "Nero Noctis"
        ],
        "rating": 4.7,
        "reviews": 99,
        "featured": false
      },
      {
        "id": "lamborghini-murcielago",
        "name": "Lamborghini Murciélago LP670-4 SV",
        "brand": "Lamborghini",
        "model": "Murciélago LP670-4 SV",
        "year": 2010,
        "type": "Supercar",
        "price": 450000,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "A limited-edition V12 supercar with extreme performance.",
        "specs": {
          "engine": "6.5L V12",
          "power": "661 hp",
          "torque": "487 lb-ft",
          "acceleration": "3.2s",
          "topSpeed": "212 mph",
          "weight": "1565 kg",
          "length": "4610 mm",
          "width": "2058 mm",
          "height": "1135 mm",
          "seats": "2",
          "transmission": "6-speed E-gear",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Carbon Fiber Spoiler",
          "Lightweight Seats",
          "Navigation",
          "Sport Exhaust",
          "Launch Control"
        ],
        "colors": [
          "Arancio Atlas",
          "Giallo Orion",
          "Nero Aldebaran",
          "Bianco Isis",
          "Grigio Telesto"
        ],
        "rating": 4.9,
        "reviews": 45,
        "featured": false
      },
      {
        "id": "landrover-range-rover",
        "name": "Land Rover Range Rover",
        "brand": "Land Rover",
        "model": "Range Rover",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 104500,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "The Range Rover is the ultimate luxury SUV, blending off-road capability with on-road comfort.",
        "specs": {
          "engine": "3.0L I6 Turbo",
          "power": "395 hp",
          "torque": "406 lb-ft",
          "acceleration": "5.5s",
          "topSpeed": "155 mph",
          "weight": "2450 kg",
          "length": "5052 mm",
          "width": "2047 mm",
          "height": "1870 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Terrain Response 2",
          "Meridian Sound System",
          "Panoramic Roof",
          "Heated Seats",
          "Adaptive Cruise"
        ],
        "colors": [
          "Santorini Black",
          "Firenze Red",
          "Yulong White",
          "Eiger Grey",
          "Portofino Blue"
        ],
        "rating": 4.8,
        "reviews": 210,
        "featured": true
      },
      {
        "id": "landrover-defender",
        "name": "Land Rover Defender 110",
        "brand": "Land Rover",
        "model": "Defender 110",
        "year": 2023,
        "type": "Off-Road SUV",
        "price": 69900,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A rugged, modern off-roader with legendary capability.",
        "specs": {
          "engine": "3.0L I6 Turbo",
          "power": "395 hp",
          "torque": "406 lb-ft",
          "acceleration": "5.8s",
          "topSpeed": "119 mph",
          "weight": "2310 kg",
          "length": "5018 mm",
          "width": "2008 mm",
          "height": "1967 mm",
          "seats": "7",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Air Suspension",
          "Wade Sensing",
          "360 Camera",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Tasman Blue",
          "Gondwana Stone",
          "Pangea Green",
          "Fuji White",
          "Eiger Grey"
        ],
        "rating": 4.7,
        "reviews": 180,
        "featured": false
      },
      {
        "id": "landrover-discovery",
        "name": "Land Rover Discovery",
        "brand": "Land Rover",
        "model": "Discovery",
        "year": 2022,
        "type": "Luxury SUV",
        "price": 56800,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "A versatile luxury SUV with seating for seven and advanced tech.",
        "specs": {
          "engine": "3.0L I6 Turbo",
          "power": "355 hp",
          "torque": "369 lb-ft",
          "acceleration": "6.2s",
          "topSpeed": "130 mph",
          "weight": "2230 kg",
          "length": "4956 mm",
          "width": "2073 mm",
          "height": "1888 mm",
          "seats": "7",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Terrain Response",
          "Meridian Audio",
          "Panoramic Roof",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Namib Orange",
          "Byron Blue",
          "Fuji White",
          "Santorini Black",
          "Eiger Grey"
        ],
        "rating": 4.6,
        "reviews": 99,
        "featured": false
      },
      {
        "id": "landrover-evoque",
        "name": "Range Rover Evoque",
        "brand": "Land Rover",
        "model": "Evoque",
        "year": 2023,
        "type": "Compact SUV",
        "price": 45600,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "A stylish compact SUV with luxury features and off-road ability.",
        "specs": {
          "engine": "2.0L Turbo I4",
          "power": "246 hp",
          "torque": "269 lb-ft",
          "acceleration": "7.0s",
          "topSpeed": "143 mph",
          "weight": "1750 kg",
          "length": "4371 mm",
          "width": "1996 mm",
          "height": "1649 mm",
          "seats": "5",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "ClearSight Mirror",
          "Panoramic Roof",
          "Heated Seats",
          "Navigation",
          "Apple CarPlay"
        ],
        "colors": [
          "Seoul Pearl Silver",
          "Firenze Red",
          "Yulong White",
          "Eiger Grey",
          "Santorini Black"
        ],
        "rating": 4.5,
        "reviews": 70,
        "featured": false
      },
      {
        "id": "landrover-velar",
        "name": "Range Rover Velar",
        "brand": "Land Rover",
        "model": "Velar",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 60400,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A sleek, modern SUV with advanced tech and refined style.",
        "specs": {
          "engine": "2.0L Turbo I4",
          "power": "247 hp",
          "torque": "269 lb-ft",
          "acceleration": "6.4s",
          "topSpeed": "135 mph",
          "weight": "1840 kg",
          "length": "4797 mm",
          "width": "2041 mm",
          "height": "1683 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Touch Pro Duo",
          "Meridian Audio",
          "Panoramic Roof",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Byron Blue",
          "Santorini Black",
          "Yulong White",
          "Eiger Grey",
          "Firenze Red"
        ],
        "rating": 4.7,
        "reviews": 88,
        "featured": false
      },
      {
        "id": "maserati-levante",
        "name": "Maserati Levante",
        "brand": "Maserati",
        "model": "Levante",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 78990,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "The Maserati Levante is a luxury SUV with Italian style and performance.",
        "specs": {
          "engine": "3.0L Twin-Turbo V6",
          "power": "424 hp",
          "torque": "428 lb-ft",
          "acceleration": "5.0s",
          "topSpeed": "164 mph",
          "weight": "2109 kg",
          "length": "5005 mm",
          "width": "1981 mm",
          "height": "1693 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Skyhook Suspension",
          "Bowers & Wilkins Audio",
          "Heated Steering Wheel",
          "Remote Start",
          "Navigation"
        ],
        "colors": [
          "Bianco",
          "Nero",
          "Blu Emozione",
          "Grigio Maratea",
          "Rosso Rubino"
        ],
        "rating": 4.6,
        "reviews": 150,
        "featured": true
      },
      {
        "id": "maserati-ghibli",
        "name": "Maserati Ghibli",
        "brand": "Maserati",
        "model": "Ghibli",
        "year": 2022,
        "type": "Luxury Sedan",
        "price": 74990,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A sporty luxury sedan with Italian flair and turbocharged power.",
        "specs": {
          "engine": "3.0L Twin-Turbo V6",
          "power": "424 hp",
          "torque": "428 lb-ft",
          "acceleration": "4.7s",
          "topSpeed": "178 mph",
          "weight": "1810 kg",
          "length": "4971 mm",
          "width": "1945 mm",
          "height": "1461 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Skyhook Suspension",
          "Harman Kardon Audio",
          "Heated Seats",
          "Remote Start",
          "Navigation"
        ],
        "colors": [
          "Blu Emozione",
          "Grigio Maratea",
          "Nero",
          "Rosso Folgore",
          "Bianco"
        ],
        "rating": 4.5,
        "reviews": 110,
        "featured": false
      },
      {
        "id": "maserati-quattroporte",
        "name": "Maserati Quattroporte",
        "brand": "Maserati",
        "model": "Quattroporte",
        "year": 2023,
        "type": "Luxury Sedan",
        "price": 104890,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "A flagship luxury sedan with Italian design and V6 or V8 power.",
        "specs": {
          "engine": "3.8L Twin-Turbo V8",
          "power": "580 hp",
          "torque": "538 lb-ft",
          "acceleration": "4.2s",
          "topSpeed": "203 mph",
          "weight": "1900 kg",
          "length": "5262 mm",
          "width": "1948 mm",
          "height": "1481 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Bowers & Wilkins Audio",
          "Heated Steering Wheel",
          "Remote Start",
          "Navigation"
        ],
        "colors": [
          "Grigio Maratea",
          "Nero",
          "Blu Passione",
          "Rosso Folgore",
          "Bianco"
        ],
        "rating": 4.7,
        "reviews": 90,
        "featured": false
      },
      {
        "id": "maserati-mc20",
        "name": "Maserati MC20",
        "brand": "Maserati",
        "model": "MC20",
        "year": 2023,
        "type": "Supercar",
        "price": 212000,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "A mid-engine supercar with a twin-turbo V6 and carbon fiber chassis.",
        "specs": {
          "engine": "3.0L Twin-Turbo V6",
          "power": "621 hp",
          "torque": "538 lb-ft",
          "acceleration": "2.9s",
          "topSpeed": "202 mph",
          "weight": "1500 kg",
          "length": "4669 mm",
          "width": "1965 mm",
          "height": "1224 mm",
          "seats": "2",
          "transmission": "8-speed DCT",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Carbon Fiber Chassis",
          "Launch Control",
          "Brembo Brakes",
          "Navigation",
          "Apple CarPlay"
        ],
        "colors": [
          "Blu Infinito",
          "Rosso Vincente",
          "Giallo Genio",
          "Grigio Mistero",
          "Bianco Audace"
        ],
        "rating": 4.9,
        "reviews": 60,
        "featured": true
      },
      {
        "id": "maserati-granturismo",
        "name": "Maserati GranTurismo",
        "brand": "Maserati",
        "model": "GranTurismo",
        "year": 2022,
        "type": "Grand Tourer",
        "price": 134300,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A stylish grand tourer with a naturally aspirated V8.",
        "specs": {
          "engine": "4.7L V8",
          "power": "454 hp",
          "torque": "384 lb-ft",
          "acceleration": "4.7s",
          "topSpeed": "186 mph",
          "weight": "1870 kg",
          "length": "4910 mm",
          "width": "1915 mm",
          "height": "1353 mm",
          "seats": "4",
          "transmission": "6-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Skyhook Suspension",
          "Bose Audio",
          "Heated Seats",
          "Navigation",
          "Leather Interior"
        ],
        "colors": [
          "Blu Sofisticato",
          "Rosso Trionfale",
          "Grigio Granito",
          "Nero Carbonio",
          "Bianco Eldorado"
        ],
        "rating": 4.8,
        "reviews": 80,
        "featured": false
      },
      {
        "id": "mercedes-amg-gt",
        "name": "Mercedes-AMG GT",
        "brand": "Mercedes-Benz",
        "model": "AMG GT",
        "year": 2024,
        "type": "Sports Car",
        "price": 93500,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "The Mercedes-AMG GT is a handcrafted sports car that embodies the spirit of AMG.",
        "specs": {
          "engine": "4.0L Biturbo V8",
          "power": "469 hp",
          "torque": "465 lb-ft",
          "acceleration": "3.7s",
          "topSpeed": "198 mph",
          "weight": "1645 kg",
          "length": "4544 mm",
          "width": "1939 mm",
          "height": "1287 mm",
          "seats": "2",
          "transmission": "9-speed AMG Speedshift",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "AMG DYNAMIC PLUS Package",
          "AMG Performance Seats",
          "Burmester Surround Sound",
          "AMG Track Pace",
          "Head-up Display"
        ],
        "colors": [
          "Polar White",
          "Obsidian Black",
          "Selenite Grey",
          "Designo Selenite Grey",
          "Designo Cardinal Red"
        ],
        "rating": 4.8,
        "reviews": 756,
        "featured": true
      },
      {
        "id": "mercedes-c63s",
        "name": "Mercedes-AMG C63 S",
        "brand": "Mercedes-Benz",
        "model": "C63 S",
        "year": 2022,
        "type": "Performance Sedan",
        "price": 78000,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A high-performance sedan with a twin-turbo V8 and luxury features.",
        "specs": {
          "engine": "4.0L Biturbo V8",
          "power": "503 hp",
          "torque": "516 lb-ft",
          "acceleration": "3.8s",
          "topSpeed": "180 mph",
          "weight": "1725 kg",
          "length": "4751 mm",
          "width": "1839 mm",
          "height": "1407 mm",
          "seats": "5",
          "transmission": "9-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "AMG Ride Control",
          "Burmester Audio",
          "Heated Seats",
          "Navigation",
          "Panoramic Roof"
        ],
        "colors": [
          "Selenite Grey",
          "Polar White",
          "Obsidian Black",
          "Brilliant Blue",
          "Designo Diamond White"
        ],
        "rating": 4.7,
        "reviews": 210,
        "featured": false
      },
      {
        "id": "mercedes-eqs",
        "name": "Mercedes-Benz EQS",
        "brand": "Mercedes-Benz",
        "model": "EQS",
        "year": 2023,
        "type": "Electric Sedan",
        "price": 102310,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "A luxury electric sedan with advanced tech and long range.",
        "specs": {
          "engine": "Dual Electric Motors",
          "power": "516 hp",
          "torque": "631 lb-ft",
          "acceleration": "4.1s",
          "topSpeed": "130 mph",
          "weight": "2480 kg",
          "length": "5216 mm",
          "width": "1926 mm",
          "height": "1512 mm",
          "seats": "5",
          "transmission": "Single-speed",
          "drivetrain": "All-wheel drive",
          "fuelType": "Electric"
        },
        "features": [
          "MBUX Hyperscreen",
          "Burmester Audio",
          "Heated/Cooled Seats",
          "Navigation",
          "Panoramic Roof"
        ],
        "colors": [
          "Obsidian Black",
          "Polar White",
          "Selenite Grey",
          "Nautical Blue",
          "MANUFAKTUR Cardinal Red"
        ],
        "rating": 4.9,
        "reviews": 180,
        "featured": true
      },
      {
        "id": "mercedes-gclass",
        "name": "Mercedes-Benz G-Class",
        "brand": "Mercedes-Benz",
        "model": "G 550",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 139900,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "An iconic luxury SUV with off-road capability and timeless design.",
        "specs": {
          "engine": "4.0L Biturbo V8",
          "power": "416 hp",
          "torque": "450 lb-ft",
          "acceleration": "5.6s",
          "topSpeed": "130 mph",
          "weight": "2560 kg",
          "length": "4817 mm",
          "width": "1931 mm",
          "height": "1969 mm",
          "seats": "5",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Three Locking Differentials",
          "Burmester Audio",
          "Heated/Cooled Seats",
          "Navigation",
          "Panoramic Roof"
        ],
        "colors": [
          "Obsidian Black",
          "Polar White",
          "Emerald Green",
          "Selenite Grey",
          "G manufaktur Olive"
        ],
        "rating": 4.8,
        "reviews": 99,
        "featured": false
      },
      {
        "id": "mercedes-sclass",
        "name": "Mercedes-Benz S-Class",
        "brand": "Mercedes-Benz",
        "model": "S 580",
        "year": 2023,
        "type": "Luxury Sedan",
        "price": 117700,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A flagship luxury sedan with advanced tech and supreme comfort.",
        "specs": {
          "engine": "4.0L Biturbo V8",
          "power": "496 hp",
          "torque": "516 lb-ft",
          "acceleration": "4.7s",
          "topSpeed": "130 mph",
          "weight": "2250 kg",
          "length": "5469 mm",
          "width": "1921 mm",
          "height": "1510 mm",
          "seats": "4",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Burmester 4D Sound",
          "Energizing Comfort",
          "Panoramic Sunroof",
          "Massage Seats"
        ],
        "colors": [
          "Obsidian Black",
          "Diamond White",
          "Emerald Green",
          "Rubellite Red",
          "Kalahari Gold"
        ],
        "rating": 4.8,
        "reviews": 30,
        "featured": true
      },
      {
        "id": "maybach-s680",
        "name": "Mercedes-Maybach S 680",
        "brand": "Mercedes-Maybach",
        "model": "S 680",
        "year": 2023,
        "type": "Luxury Sedan",
        "price": 229000,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "The Mercedes-Maybach S 680 is the pinnacle of luxury and comfort.",
        "specs": {
          "engine": "6.0L V12 Biturbo",
          "power": "621 hp",
          "torque": "738 lb-ft",
          "acceleration": "4.4s",
          "topSpeed": "155 mph",
          "weight": "2350 kg",
          "length": "5469 mm",
          "width": "1921 mm",
          "height": "1510 mm",
          "seats": "4",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Burmester 4D Sound",
          "Energizing Comfort",
          "Panoramic Sunroof",
          "Massage Seats"
        ],
        "colors": [
          "Obsidian Black",
          "Diamond White",
          "Emerald Green",
          "Rubellite Red",
          "Kalahari Gold"
        ],
        "rating": 4.9,
        "reviews": 99,
        "featured": true
      },
      {
        "id": "maybach-gls600",
        "name": "Mercedes-Maybach GLS 600",
        "brand": "Mercedes-Maybach",
        "model": "GLS 600",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 170000,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A luxury SUV with Maybach refinement and V8 power.",
        "specs": {
          "engine": "4.0L V8 Biturbo",
          "power": "550 hp",
          "torque": "538 lb-ft",
          "acceleration": "4.8s",
          "topSpeed": "155 mph",
          "weight": "2785 kg",
          "length": "5205 mm",
          "width": "2157 mm",
          "height": "1823 mm",
          "seats": "4",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Burmester 3D Sound",
          "Energizing Comfort",
          "Panoramic Sunroof",
          "Massage Seats"
        ],
        "colors": [
          "Obsidian Black",
          "Diamond White",
          "Emerald Green",
          "Rubellite Red",
          "Kalahari Gold"
        ],
        "rating": 4.8,
        "reviews": 80,
        "featured": true
      },
      {
        "id": "maybach-s560",
        "name": "Mercedes-Maybach S 560",
        "brand": "Mercedes-Maybach",
        "model": "S 560",
        "year": 2020,
        "type": "Luxury Sedan",
        "price": 173000,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "A luxury sedan with V8 power and Maybach exclusivity.",
        "specs": {
          "engine": "4.0L V8 Biturbo",
          "power": "463 hp",
          "torque": "516 lb-ft",
          "acceleration": "4.8s",
          "topSpeed": "130 mph",
          "weight": "2250 kg",
          "length": "5462 mm",
          "width": "1899 mm",
          "height": "1498 mm",
          "seats": "4",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Burmester Audio",
          "Energizing Comfort",
          "Panoramic Sunroof",
          "Massage Seats"
        ],
        "colors": [
          "Obsidian Black",
          "Diamond White",
          "Emerald Green",
          "Rubellite Red",
          "Kalahari Gold"
        ],
        "rating": 4.7,
        "reviews": 60,
        "featured": false
      },
      {
        "id": "maybach-s650",
        "name": "Mercedes-Maybach S 650",
        "brand": "Mercedes-Maybach",
        "model": "S 650",
        "year": 2020,
        "type": "Luxury Sedan",
        "price": 202550,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "A V12-powered luxury sedan with ultimate comfort and exclusivity.",
        "specs": {
          "engine": "6.0L V12 Biturbo",
          "power": "621 hp",
          "torque": "738 lb-ft",
          "acceleration": "4.6s",
          "topSpeed": "155 mph",
          "weight": "2360 kg",
          "length": "5462 mm",
          "width": "1899 mm",
          "height": "1498 mm",
          "seats": "4",
          "transmission": "7-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Burmester Audio",
          "Energizing Comfort",
          "Panoramic Sunroof",
          "Massage Seats"
        ],
        "colors": [
          "Obsidian Black",
          "Diamond White",
          "Emerald Green",
          "Rubellite Red",
          "Kalahari Gold"
        ],
        "rating": 4.9,
        "reviews": 40,
        "featured": false
      },
      {
        "id": "maybach-s580",
        "name": "Mercedes-Maybach S 580",
        "brand": "Mercedes-Maybach",
        "model": "S 580",
        "year": 2023,
        "type": "Luxury Sedan",
        "price": 184900,
        "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop",
        "description": "A new generation of Maybach luxury with V8 power and advanced tech.",
        "specs": {
          "engine": "4.0L V8 Biturbo",
          "power": "496 hp",
          "torque": "516 lb-ft",
          "acceleration": "4.7s",
          "topSpeed": "130 mph",
          "weight": "2250 kg",
          "length": "5469 mm",
          "width": "1921 mm",
          "height": "1510 mm",
          "seats": "4",
          "transmission": "9-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Executive Rear Seats",
          "Burmester 4D Sound",
          "Energizing Comfort",
          "Panoramic Sunroof",
          "Massage Seats"
        ],
        "colors": [
          "Obsidian Black",
          "Diamond White",
          "Emerald Green",
          "Rubellite Red",
          "Kalahari Gold"
        ],
        "rating": 4.8,
        "reviews": 30,
        "featured": true
      },
      {
        "id": "porsche-911",
        "name": "Porsche 911",
        "brand": "Porsche",
        "model": "911",
        "year": 2024,
        "type": "Sports Car",
        "price": 106100,
        "image": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop",
        "description": "The Porsche 911 is the iconic sports car that has defined automotive excellence for over 50 years.",
        "specs": {
          "engine": "3.0L Twin-Turbo Flat-6",
          "power": "379 hp",
          "torque": "331 lb-ft",
          "acceleration": "3.8s",
          "topSpeed": "182 mph",
          "weight": "1510 kg",
          "length": "4519 mm",
          "width": "1852 mm",
          "height": "1297 mm",
          "seats": "4",
          "transmission": "8-speed PDK",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Porsche Active Suspension",
          "Sport Chrono Package",
          "PASM Sport Suspension",
          "20-inch Wheels",
          "Sport Exhaust System"
        ],
        "colors": [
          "White",
          "Black",
          "GT Silver Metallic",
          "Miami Blue",
          "Guards Red"
        ],
        "rating": 4.9,
        "reviews": 1234,
        "featured": true
      },
      {
        "id": "porsche-taycan",
        "name": "Porsche Taycan Turbo S",
        "brand": "Porsche",
        "model": "Taycan Turbo S",
        "year": 2023,
        "type": "Electric Sports Car",
        "price": 185000,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "A high-performance electric sports car with instant torque and Porsche handling.",
        "specs": {
          "engine": "Dual Electric Motors",
          "power": "750 hp",
          "torque": "774 lb-ft",
          "acceleration": "2.6s",
          "topSpeed": "162 mph",
          "weight": "2295 kg",
          "length": "4963 mm",
          "width": "1966 mm",
          "height": "1378 mm",
          "seats": "4",
          "transmission": "2-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Electric"
        },
        "features": [
          "Porsche Electric Sport Sound",
          "Adaptive Air Suspension",
          "Bose Surround Sound",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Frozen Blue",
          "Jet Black",
          "Dolomite Silver",
          "Carmine Red",
          "White"
        ],
        "rating": 4.8,
        "reviews": 210,
        "featured": true
      },
      {
        "id": "porsche-cayenne",
        "name": "Porsche Cayenne Turbo",
        "brand": "Porsche",
        "model": "Cayenne Turbo",
        "year": 2023,
        "type": "Luxury SUV",
        "price": 135900,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "A luxury SUV with sports car performance and Porsche DNA.",
        "specs": {
          "engine": "4.0L Twin-Turbo V8",
          "power": "541 hp",
          "torque": "567 lb-ft",
          "acceleration": "3.7s",
          "topSpeed": "177 mph",
          "weight": "2175 kg",
          "length": "4929 mm",
          "width": "1983 mm",
          "height": "1696 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Adaptive Air Suspension",
          "Porsche Dynamic Chassis Control",
          "Bose Surround Sound",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Jet Black",
          "Carrara White",
          "Quartzite Grey",
          "Mahogany Metallic",
          "Moonlight Blue"
        ],
        "rating": 4.7,
        "reviews": 180,
        "featured": false
      },
      {
        "id": "porsche-panamera",
        "name": "Porsche Panamera GTS",
        "brand": "Porsche",
        "model": "Panamera GTS",
        "year": 2022,
        "type": "Luxury Sedan",
        "price": 130700,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "A luxury sedan with sports car performance and four-door practicality.",
        "specs": {
          "engine": "4.0L Twin-Turbo V8",
          "power": "473 hp",
          "torque": "457 lb-ft",
          "acceleration": "3.9s",
          "topSpeed": "181 mph",
          "weight": "1995 kg",
          "length": "5049 mm",
          "width": "1937 mm",
          "height": "1423 mm",
          "seats": "4",
          "transmission": "8-speed PDK",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Adaptive Air Suspension",
          "Sport Chrono Package",
          "Bose Surround Sound",
          "Heated Seats",
          "Navigation"
        ],
        "colors": [
          "Carmine Red",
          "Jet Black",
          "Dolomite Silver",
          "White",
          "Night Blue"
        ],
        "rating": 4.8,
        "reviews": 99,
        "featured": false
      },
      {
        "id": "porsche-macan",
        "name": "Porsche Macan GTS",
        "brand": "Porsche",
        "model": "Macan GTS",
        "year": 2023,
        "type": "Compact SUV",
        "price": 79900,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "A compact SUV with sporty handling and Porsche performance.",
        "specs": {
          "engine": "2.9L Twin-Turbo V6",
          "power": "434 hp",
          "torque": "406 lb-ft",
          "acceleration": "4.3s",
          "topSpeed": "169 mph",
          "weight": "1895 kg",
          "length": "4726 mm",
          "width": "1922 mm",
          "height": "1621 mm",
          "seats": "5",
          "transmission": "7-speed PDK",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Sport Chrono Package",
          "Bose Surround Sound",
          "Heated Seats",
          "Navigation",
          "Panoramic Roof"
        ],
        "colors": [
          "Papaya Metallic",
          "Jet Black",
          "White",
          "Dolomite Silver",
          "Night Blue"
        ],
        "rating": 4.7,
        "reviews": 70,
        "featured": false
      },
      {
        "id": "rollsroyce-phantom",
        "name": "Rolls-Royce Phantom",
        "brand": "Rolls-Royce",
        "model": "Phantom",
        "year": 2024,
        "type": "Luxury Sedan",
        "price": 460000,
        "image": "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=800&h=600&fit=crop",
        "description": "The Rolls-Royce Phantom is the ultimate expression of luxury, craftsmanship, and prestige.",
        "specs": {
          "engine": "6.75L V12",
          "power": "563 hp",
          "torque": "664 lb-ft",
          "acceleration": "5.1s",
          "topSpeed": "155 mph",
          "weight": "2560 kg",
          "length": "5982 mm",
          "width": "2018 mm",
          "height": "1646 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Starlight Headliner",
          "Lambswool Floor Mats",
          "Rear Theatre Configuration",
          "Bespoke Audio",
          "Coach Doors"
        ],
        "colors": [
          "Arctic White",
          "Black Diamond",
          "Belladonna Purple",
          "English White",
          "Metropolitan Blue"
        ],
        "rating": 4.9,
        "reviews": 45,
        "featured": true
      },
      {
        "id": "rollsroyce-ghost",
        "name": "Rolls-Royce Ghost",
        "brand": "Rolls-Royce",
        "model": "Ghost",
        "year": 2023,
        "type": "Luxury Sedan",
        "price": 340000,
        "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&h=600&fit=crop",
        "description": "The Rolls-Royce Ghost blends contemporary luxury with effortless performance.",
        "specs": {
          "engine": "6.75L V12",
          "power": "563 hp",
          "torque": "627 lb-ft",
          "acceleration": "4.6s",
          "topSpeed": "155 mph",
          "weight": "2490 kg",
          "length": "5546 mm",
          "width": "1978 mm",
          "height": "1571 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Illuminated Grille",
          "Rear Massage Seats",
          "Bespoke Audio",
          "Spirit of Ecstasy Rotary Controller",
          "Soft Close Doors"
        ],
        "colors": [
          "Tempest Grey",
          "Arctic White",
          "Black",
          "Jubilee Silver",
          "Midnight Sapphire"
        ],
        "rating": 4.8,
        "reviews": 38,
        "featured": true
      },
      {
        "id": "rollsroyce-cullinan",
        "name": "Rolls-Royce Cullinan",
        "brand": "Rolls-Royce",
        "model": "Cullinan",
        "year": 2024,
        "type": "Luxury SUV",
        "price": 355000,
        "image": "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop",
        "description": "The Rolls-Royce Cullinan is the most luxurious SUV, offering supreme comfort and capability.",
        "specs": {
          "engine": "6.75L V12",
          "power": "563 hp",
          "torque": "627 lb-ft",
          "acceleration": "4.8s",
          "topSpeed": "155 mph",
          "weight": "2660 kg",
          "length": "5341 mm",
          "width": "2000 mm",
          "height": "1835 mm",
          "seats": "5",
          "transmission": "8-speed Automatic",
          "drivetrain": "All-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Viewing Suite",
          "Panoramic Sunroof",
          "Bespoke Audio",
          "Lambswool Floor Mats",
          "Rear Picnic Tables"
        ],
        "colors": [
          "Tuscan Sun",
          "Arctic White",
          "Black",
          "Petra Gold",
          "Dark Emerald"
        ],
        "rating": 4.9,
        "reviews": 29,
        "featured": true
      },
      {
        "id": "rollsroyce-wraith",
        "name": "Rolls-Royce Wraith",
        "brand": "Rolls-Royce",
        "model": "Wraith",
        "year": 2022,
        "type": "Luxury Coupe",
        "price": 343000,
        "image": "https://images.unsplash.com/photo-1511918984145-48de785d4c4e?w=800&h=600&fit=crop",
        "description": "The Rolls-Royce Wraith is a grand tourer that combines power, luxury, and style.",
        "specs": {
          "engine": "6.6L Twin-Turbo V12",
          "power": "624 hp",
          "torque": "605 lb-ft",
          "acceleration": "4.4s",
          "topSpeed": "155 mph",
          "weight": "2440 kg",
          "length": "5285 mm",
          "width": "1947 mm",
          "height": "1507 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Starlight Headliner",
          "Bespoke Audio",
          "Coach Doors",
          "Lambswool Floor Mats",
          "Satellite Aided Transmission"
        ],
        "colors": [
          "English White",
          "Black",
          "Silver",
          "Royal Blue",
          "Arctic White"
        ],
        "rating": 4.7,
        "reviews": 22,
        "featured": false
      },
      {
        "id": "rollsroyce-dawn",
        "name": "Rolls-Royce Dawn",
        "brand": "Rolls-Royce",
        "model": "Dawn",
        "year": 2022,
        "type": "Luxury Convertible",
        "price": 356000,
        "image": "https://images.unsplash.com/photo-1464983953574-0892a716854b?w=800&h=600&fit=crop",
        "description": "The Rolls-Royce Dawn is a luxury convertible that offers open-top motoring in supreme comfort.",
        "specs": {
          "engine": "6.6L Twin-Turbo V12",
          "power": "563 hp",
          "torque": "605 lb-ft",
          "acceleration": "4.9s",
          "topSpeed": "155 mph",
          "weight": "2560 kg",
          "length": "5285 mm",
          "width": "1947 mm",
          "height": "1502 mm",
          "seats": "4",
          "transmission": "8-speed Automatic",
          "drivetrain": "Rear-wheel drive",
          "fuelType": "Gasoline"
        },
        "features": [
          "Bespoke Audio",
          "Coach Doors",
          "Lambswool Floor Mats",
          "Heated Seats",
          "Soft Top"
        ],
        "colors": [
          "Arctic White",
          "Black",
          "Silver",
          "Metropolitan Blue",
          "English White"
        ],
        "rating": 4.8,
        "reviews": 18,
        "featured": false
      }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = carData;
} 